# Generated by Django 5.0.14 on 2025-11-01 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("ACCESS", "Access"),
                            ("EXPORT", "Export"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.IntegerField(db_index=True)),
                ("object_repr", models.CharField(max_length=200)),
                (
                    "changes",
                    models.JSONField(
                        default=dict, help_text="Before/after state for event replay"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for the action"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_logs_model_n_656046_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_logs_action_474804_idx",
                    ),
                ],
            },
        ),
    ]
