# Generated by Django 5.0.14 on 2025-11-02 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_notification_task"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_c4e471_idx",
            old_name="notificatio_user_id_is_read_created_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_assigne_298451_idx",
            old_name="tasks_assigned_status_priority_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_due_dat_6498c2_idx",
            old_name="tasks_due_date_status_idx",
        ),
    ]
