# Generated by Django 5.0.14 on 2025-11-01 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("centers", "0002_centerhead"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "questions",
                    models.JSONField(
                        default=list,
                        help_text="List of survey questions with type and options",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Published surveys can be sent to students",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for global surveys",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveys",
                        to="centers.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="User who last modified this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Survey",
                "verbose_name_plural": "Feedback Surveys",
                "db_table": "feedback_surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique token for accessing the survey",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict, help_text="Student's answers to survey questions"
                    ),
                ),
                (
                    "satisfaction_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Overall satisfaction score (1-5)",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="User who last modified this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback_responses",
                        to="students.student",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="feedback.feedbacksurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Response",
                "verbose_name_plural": "Feedback Responses",
                "db_table": "feedback_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="feedbacksurvey",
            index=models.Index(
                fields=["is_active", "is_published"],
                name="feedback_su_is_acti_a3df71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedbacksurvey",
            index=models.Index(
                fields=["valid_from", "valid_until"],
                name="feedback_su_valid_f_84bcf9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackresponse",
            index=models.Index(fields=["token"], name="feedback_re_token_71fb9c_idx"),
        ),
        migrations.AddIndex(
            model_name="feedbackresponse",
            index=models.Index(
                fields=["is_completed"], name="feedback_re_is_comp_d426b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackresponse",
            index=models.Index(
                fields=["submitted_at"], name="feedback_re_submitt_c2665d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedbackresponse",
            unique_together={("survey", "student")},
        ),
    ]
