# Generated by Django 5.0.14 on 2025-11-04 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0002_centerhead"),
        ("faculty", "0002_initial"),
        ("feedback", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique token for accessing the feedback form",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "teaching_quality",
                    models.IntegerField(
                        blank=True,
                        help_text="How would you rate the faculty's teaching quality? (1-5)",
                        null=True,
                    ),
                ),
                (
                    "subject_knowledge",
                    models.IntegerField(
                        blank=True,
                        help_text="How knowledgeable is the faculty about the subject? (1-5)",
                        null=True,
                    ),
                ),
                (
                    "explanation_clarity",
                    models.IntegerField(
                        blank=True,
                        help_text="How clear are the faculty's explanations? (1-5)",
                        null=True,
                    ),
                ),
                (
                    "student_engagement",
                    models.IntegerField(
                        blank=True,
                        help_text="How well does the faculty engage and motivate you? (1-5)",
                        null=True,
                    ),
                ),
                (
                    "doubt_resolution",
                    models.IntegerField(
                        blank=True,
                        help_text="How effectively does the faculty resolve your doubts? (1-5)",
                        null=True,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall feedback score (1-5)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Additional comments or suggestions"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("whatsapp_sent_at", models.DateTimeField(blank=True, null=True)),
                ("link_opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_feedbacks",
                        to="centers.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedbacks",
                        to="faculty.faculty",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="User who last modified this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_feedbacks",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty Feedback",
                "verbose_name_plural": "Faculty Feedbacks",
                "db_table": "faculty_feedbacks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="faculty_fee_token_2a4a3d_idx"),
                    models.Index(
                        fields=["faculty", "is_completed"],
                        name="faculty_fee_faculty_dbdf7c_idx",
                    ),
                    models.Index(
                        fields=["student", "faculty"],
                        name="faculty_fee_student_6d41fd_idx",
                    ),
                    models.Index(
                        fields=["center", "submitted_at"],
                        name="faculty_fee_center__7734fe_idx",
                    ),
                ],
            },
        ),
    ]
