# Generated by Django 5.0.14 on 2025-11-01 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="subject",
            name="center",
        ),
    ]
