# Generated by Django 5.0.14 on 2025-11-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("in_time", models.TimeField()),
                ("out_time", models.TimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="Session duration in minutes"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about what was covered, student progress, etc.",
                    ),
                ),
                (
                    "is_backdated",
                    models.BooleanField(
                        default=False,
                        help_text="Was this attendance marked for a past date?",
                    ),
                ),
                (
                    "backdated_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for backdating (required if backdated)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance_records",
                "ordering": ["-date", "-in_time"],
            },
        ),
    ]
