# Generated by Django 5.0.14 on 2025-11-01 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("faculty", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="faculty_members", to="subjects.subject"
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "faculty"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
